### ISSUE TITLE
INFO Formato para JSON de Visualización-Resultados

### ISSUE THREAD

**Issue by danmarrod** [AgoraUS1516/G01#6]
Buenas, somos el equipo de Visualización-Resultados, para poder almacenar y mostrar las resultados correctamente necesitamos el formato json final que tendrán las peticiones que os realizaremos desde nuestro subsistema.

Gracias.

**Comment by Lammerlord92** [comment]
Buenas, de momento este es el ejemplo de JSon que tenemos puesto:
{"nombre":"Encuesta 1","ultimaModififacion":"Dec 22, 2015 1:35:26 PM","recuento":[{"cp":41012,"pregunta":"¿Cual es tu intencion voto?","opcion":"podemos","opcionCount":1,"id":32769,"version":0},{"cp":41013,"pregunta":"¿Cual es tu intencion voto?","opcion":"Ciudadanos","opcionCount":1,"id":32770,"version":0},{"cp":41013,"pregunta":"¿Cual es tu intencion voto?","opcion":"Podemos","opcionCount":1,"id":32771,"version":0},{"cp":41011,"pregunta":"¿Cual es tu intencion voto?","opcion":"PSOE","opcionCount":1,"id":32772,"version":0},{"cp":41012,"pregunta":"¿Podrías evaluar del 1 al 10 a los actuales políticos?","opcion":"1","opcionCount":1,"id":32776,"version":0},{"cp":41013,"pregunta":"¿Podrías evaluar del 1 al 10 a los actuales políticos?","opcion":"1","opcionCount":1,"id":32777,"version":0},{"cp":41013,"pregunta":"¿Podrías evaluar del 1 al 10 a los actuales políticos?","opcion":"7","opcionCount":1,"id":32778,"version":0},{"cp":41011,"pregunta":"¿Podrías evaluar del 1 al 10 a los actuales políticos?","opcion":"1","opcionCount":1,"id":32779,"version":0},{"cp":41012,"pregunta":"¿Cual es el candidato que menos te gusta?","opcion":"Albert Rivera","opcionCount":1,"id":32782,"version":0},{"cp":41013,"pregunta":"¿Cual es el candidato que menos te gusta?","opcion":"Mariano Rajoy","opcionCount":1,"id":32783,"version":0},{"cp":41013,"pregunta":"¿Cual es el candidato que menos te gusta?","opcion":"Pedro Sánchez","opcionCount":1,"id":32784,"version":0},{"cp":41011,"pregunta":"¿Cual es el candidato que menos te gusta?","opcion":"Mariano Rajoy","opcionCount":1,"id":32785,"version":0},{"pregunta":"¿Cual es tu intencion voto?","opcion":"Ciudadanos","opcionCount":1,"id":32773,"version":0},{"pregunta":"¿Cual es tu intencion voto?","opcion":"podemos","opcionCount":2,"id":32774,"version":0},{"pregunta":"¿Cual es tu intencion voto?","opcion":"PSOE","opcionCount":1,"id":32775,"version":0},{"pregunta":"¿Podrías evaluar del 1 al 10 a los actuales políticos?","opcion":"1","opcionCount":3,"id":32780,"version":0},{"pregunta":"¿Podrías evaluar del 1 al 10 a los actuales políticos?","opcion":"7","opcionCount":1,"id":32781,"version":0},{"pregunta":"¿Cual es el candidato que menos te gusta?","opcion":"Albert Rivera","opcionCount":1,"id":32786,"version":0},{"pregunta":"¿Cual es el candidato que menos te gusta?","opcion":"Mariano Rajoy","opcionCount":2,"id":32787,"version":0},{"pregunta":"¿Cual es el candidato que menos te gusta?","opcion":"Pedro Sánchez","opcionCount":1,"id":32788,"version":0}],"id":32768,"version":1}

Las dudas todavía son el tema de la pregunta (si lo vamos a llevar como id) y si vamos a almacenar nosotros los resultados de cada recuento, si no es así, quitaríamos las id y versiones (que no creo que os influya). De momento hay dos tipos de recuento por pregunta, una con CP y otra general (sin CP), si preferís que quitemos el que no tiene código postal, danos un toque.

**Comment by danmarrod** [comment]
Muchas gracias, cerramos la incidencia, si ha habido algún cambio por favor notificarnoslo. Un saludo.
