### ISSUE TITLE
INFO: Despliegue de la aplicación

### ISSUE THREAD

**Issue by danmarrod** [AgoraUS1516/G01#7]
Buenas, para probar si funciona la integración con vuestro subsistema según el formato json propuesto ¿tenéis desplegado el sistema en algún sitio para poder realizar las peticiones?

Un saludo.

**Comment by juanoide** [comment]
¿Quien eres?

**Comment by Lammerlord92** [comment]
No, no pudimos desplegar

**Comment by danmarrod** [comment]
OK no problem. Si en la mejora contemplais el despliegue os agradeceríamos que nos avisarais por intentar integrarnos con vosotros. Un saludo.
